### ISSUE TITLE
callback url isn't trigged 

### ISSUE THREAD

**Issue by joel** [DocRaptor/docraptor-ruby#2]
I use the pretty straightforward code below with a paid and working account on Docraptor

```
require 'docraptor'

DocRaptor.configure do |dr|
  dr.username = 'xxxxxxxx'
  dr.debugging = true
end

options = {
  name: '56cb1f67ea32542ed2000000_csv.xls',
  document_type: 'xls',
  test: false,
  callback_url: '<valid call back url>',
  document_url:  '<valid amazon url>',
  prince_options: { version: '9.0', http_timeout: '60' }
}

docraptor = DocRaptor::DocApi.new

create_response = docraptor.create_async_doc(options)
```

The server is never called.... Pretty same code works with [doc_raptor](https://rubygems.org/gems/doc_raptor`)

What is wrong here?

Thanks

**Comment by janxious** [comment]
@joel I suspect @jason-o-matic has already been in touch with you, but this was fixed by changes to DocRaptor internals, so the client libraries should be working properly now. We have also added automated regression tests to our suite to check for this and several other regressions that could have occurred.

**Comment by joel** [comment]
Indeed it's works, thanks
